# If a PR is labelled "actions" this workflow prints helpful vars

name: Actions Dev

on:
  pull_request:

jobs:

  envars:
    runs-on: ubuntu-latest
    steps:
    - name: Envars
      run: env

  contexts:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Contexts object
      run: |
        echo "action: " ${{ github.action }}
        echo "action_path: " ${{ github.action_path }}
        echo "event_name: " ${{ github.event_name }}
        echo "context object: " ${{ github }}
