name: Move assigned to In Progress
on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: Alpha
          column: In Progress
          repo-token: ${{ secrets.GITHUB_TOKEN }}
 