name: Node.js Tests

on:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      # Test with active LTS and current releasesof nodejs
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # https://docs.npmjs.com/cli/v7/commands/npm-ci (ci version of npm install)
    - name: CI install
      run: npm ci --ignore-scripts
    - name: Build (if script present)
      run: npm run build --if-present
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm run test:only
