name: Node.js Tests

on:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      # Test with active LTS and current releasesof nodejs
      matrix:
        node-version: [14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # https://docs.npmjs.com/cli/v7/commands/npm-ci (ci version of npm install)
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
